apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: cond
spec:
  version: {{ .TagName }}
  homepage: https://github.com/ahmetb/kubectl-cond
  shortDescription: View resource conditions
  description: |
    A human-friendly alternative to "kubectl describe" to view
    resource conditions for Kubernetes objects.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/ahmetb/kubectl-cond/releases/download/{{ .TagName }}/kubectl-cond_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-cond
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/ahmetb/kubectl-cond/releases/download/{{ .TagName }}/kubectl-cond_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-cond
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/ahmetb/kubectl-cond/releases/download/{{ .TagName }}/kubectl-cond_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-cond
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/ahmetb/kubectl-cond/releases/download/{{ .TagName }}/kubectl-cond_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-cond.exe
